server:
  port: 8080

spring:
  rabbitmq:
    host: 192.168.179.129
    port: 5672
    virtual-host: /mq-vs
    username: root
    password: root
    listener:
      type: simple
      simple:
        acknowledge-mode: manual # 手动签收